language: node_js
sudo: false
node_js:
- "6"
cache:
  directories:
  - node_modules
script:
- npm run ci
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
